---
collections:
  - name: community.docker
    version: ">=3.0.0"
  - name: community.general
    version: ">=8.0.0"
  - name: ansible.posix
    version: ">=1.5.0"
  - name: cisco.ios
    version: ">=8.0.0"
  - name: ansible.netcommon
    version: ">=6.0.0"
  - name: community.libvirt
    version: ">=1.3.0"
