-- LinShare Database Initialization
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
GRANT ALL PRIVILEGES ON DATABASE linshare TO linshare;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO linshare;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO linshare;
